version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - my_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    
  app:
    image: node:16.17.1
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:   
      - postgres
    volumes: 
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

volumes: 
  my_data: 
  node_modules:
